server:
  port: 8088
spring:
  cloud:
    gateway:
      routes:
        - id: customer-registration-module
          uri: 'http://localhost:8083/'
          predicates:
            - Path=/customer/api/** 
        - id: restaurant-api-admin
          uri: 'http://localhost:8081/'
          predicates:
            - Path=/food/api/admin/** 
        - id: restaurant-api-user
          uri: 'http://localhost:8082/'
          predicates:
            - Path=/food/api/user/**              
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web: 
      exposure:
        include: gateway